/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GravatarWc {
    'default'?: string;
    'email': string;
    'forceDefault'?: boolean;
    'protocol'?: "http" | "https";
    'rating'?: "g" | "pg" | "r" | "x";
    'size'?: number;
  }
  interface GravatarWcAttributes extends StencilHTMLAttributes {
    'default'?: string;
    'email'?: string;
    'forceDefault'?: boolean;
    'protocol'?: "http" | "https";
    'rating'?: "g" | "pg" | "r" | "x";
    'size'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GravatarWc': Components.GravatarWc;
  }

  interface StencilIntrinsicElements {
    'gravatar-wc': Components.GravatarWcAttributes;
  }


  interface HTMLGravatarWcElement extends Components.GravatarWc, HTMLStencilElement {}
  var HTMLGravatarWcElement: {
    prototype: HTMLGravatarWcElement;
    new (): HTMLGravatarWcElement;
  };

  interface HTMLElementTagNameMap {
    'gravatar-wc': HTMLGravatarWcElement
  }

  interface ElementTagNameMap {
    'gravatar-wc': HTMLGravatarWcElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
